# matrix 矩阵

In [24]:
import numpy as np

In [25]:
# 创建矩阵对象
ary = np.arange(6).reshape(2, 3)
m = np.mat(ary)
print(m, type(m))

[[0 1 2]
 [3 4 5]] <class 'numpy.matrix'>


In [26]:
m = np.mat('1 2 5; 6 8 4')
m

matrix([[1, 2, 5],
        [6, 8, 4]])

In [27]:
# 验证矩阵乘法规则
ary = np.arange(1, 10).reshape(3, 3)
ary

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
ary*ary

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [29]:
m = np.mat(ary)
m

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [30]:
m * m

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [31]:
# 逆矩阵
m = np.mat('1 3 5; 4 6 8; 3 6 10')
# m = np.mat('1 2 3; 4 5 6; 7 8 9')
m

matrix([[ 1,  3,  5],
        [ 4,  6,  8],
        [ 3,  6, 10]])

In [32]:
m.I

matrix([[-2.        ,  0.        ,  1.        ],
        [ 2.66666667,  0.83333333, -2.        ],
        [-1.        , -0.5       ,  1.        ]])

In [33]:
m * m.I

matrix([[ 1.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [-8.8817842e-16,  1.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  1.0000000e+00]])

In [34]:
# 解方程组
A = np.mat('3  3.2; 3.5  3.6')
B = np.mat('118.4; 135.2')
x = A.I * B
x

matrix([[16.],
        [22.]])

In [41]:
n = 38

# 使用递归实现斐波那契数列
def fibo(n):
    return 1 if n < 3 else fibo(n - 1) + fibo(n - 2)
print(fibo(n))

39088169


In [43]:
F = np.mat('1 1; 1 0')
(F**n)[0,1]

39088169